import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

// POST - Export summary as markdown text (no pandoc dependency)
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await request.json();
    const format = body.format || 'md';

    // Get the document
    const document = await db.document.findUnique({
      where: { id },
    });

    if (!document) {
      return NextResponse.json(
        { error: 'Document not found' },
        { status: 404 }
      );
    }

    if (!document.summary) {
      return NextResponse.json(
        { error: 'No summary to export' },
        { status: 400 }
      );
    }

    // Create markdown content
    const mdContent = `# ${document.filename} - Summary

**Mode:** ${document.summaryMode || 'General'}
**Generated:** ${new Date().toLocaleDateString('th-TH')}

---

${document.summary}

---

*Generated by Briefly AI*
`;

    if (format === 'pdf' || format === 'docx') {
      // PDF/DOCX export requires pandoc which is not available on Vercel
      // Return markdown with a note
      return new NextResponse(mdContent, {
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
          'Content-Disposition': `attachment; filename="${document.filename.replace(/\.[^/.]+$/, '')}_summary.md"`,
        },
      });
    }

    // Default: return as markdown
    return new NextResponse(mdContent, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${document.filename.replace(/\.[^/.]+$/, '')}_summary.md"`,
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json(
      { error: 'Failed to export document' },
      { status: 500 }
    );
  }
}
