import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, unlink, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import { randomUUID } from 'crypto';

const execAsync = promisify(exec);

const TEMP_DIR = path.join(process.cwd(), 'temp');

async function ensureTempDir() {
  if (!existsSync(TEMP_DIR)) {
    await mkdir(TEMP_DIR, { recursive: true });
  }
}

// POST - Export summary to PDF or DOCX
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await request.json();
    const format = body.format || 'pdf';

    // Get the document
    const document = await db.document.findUnique({
      where: { id },
    });

    if (!document) {
      return NextResponse.json(
        { error: 'Document not found' },
        { status: 404 }
      );
    }

    if (!document.summary) {
      return NextResponse.json(
        { error: 'No summary to export' },
        { status: 400 }
      );
    }

    await ensureTempDir();

    const uniqueId = randomUUID();
    const mdFile = path.join(TEMP_DIR, `${uniqueId}.md`);
    const outputFile = path.join(
      TEMP_DIR,
      `${uniqueId}.${format === 'pdf' ? 'pdf' : 'docx'}`
    );

    // Create markdown content
    const mdContent = `# ${document.filename} - Summary

**Mode:** ${document.summaryMode || 'General'}
**Generated:** ${new Date().toLocaleDateString('th-TH')}

---

${document.summary}

---

*Generated by DocSummarizer AI*
`;

    await writeFile(mdFile, mdContent, 'utf-8');

    try {
      if (format === 'pdf') {
        // Convert to PDF using pandoc
        await execAsync(
          `pandoc "${mdFile}" -o "${outputFile}" --pdf-engine=xelatex -V mainfont="DejaVuSans" -V geometry:margin=1in`
        );
      } else {
        // Convert to DOCX using pandoc
        await execAsync(`pandoc "${mdFile}" -o "${outputFile}"`);
      }

      // Read the file
      const { readFile } = await import('fs/promises');
      const fileBuffer = await readFile(outputFile);

      // Clean up temp files
      await unlink(mdFile);
      await unlink(outputFile);

      // Return the file
      return new NextResponse(fileBuffer, {
        headers: {
          'Content-Type':
            format === 'pdf' ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${document.filename.replace(/\.[^/.]+$/, '')}_summary.${format}"`,
        },
      });
    } catch (conversionError) {
      console.error('Conversion error:', conversionError);
      // Clean up on error
      try {
        await unlink(mdFile);
      } catch {}
      throw conversionError;
    }
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json(
      { error: 'Failed to export document' },
      { status: 500 }
    );
  }
}
